CLIENT_QUERIES = [
    "cli {prompt}",
    "cliente {prompt}",
    "Cli {prompt}",
    "Client {prompt}",
    "dame información del cliente {prompt}",
    "info del cliente {prompt}",
    "info del client {prompt}",
    "dona'm informació del client {prompt}",
    "Qui es el client {prompt}?",
    "Quien es el cliente {prompt}?",
    "Necessito dades del client {prompt}",
    "Tens informació del client {prompt}?",
    "Mostra'm el perfil del cliente {prompt}",
    "Vull saber més sobre el client {prompt}",
    "Què saps del cliente {prompt}?",
    "Com puc ajudar al cliente {prompt}?",
    "Dona'm detalls del cliente {prompt}",
    "M'agradaria veure el historial del cliente {prompt}",
    "Perfil del cliente {prompt}",
    "dame información del cliente {prompt}",
    "info del cliente {prompt}",
    "info del client {prompt}",
    "Info del Cliente {prompt}",
    "Info del cilent {prompt}",
    "dona'm informació del client {prompt}",
    "Dona'm informació del Cliente {prompt}",
    "Qui es el client {prompt}?",
    "Quien es el cliente {prompt}?",
    "Qui És El Client {prompt}?",
    "Necessito dades del client {prompt}",
    "Necesito info del Cliete {prompt}",
    "Tens informació del client {prompt}?",
    "Tienes información del Cliente {prompt}?",
    "Mostra'm el perfil del cliente {prompt}",
    "Enséñame el perfil del Clente {prompt}",
    "Vull saber més sobre el client {prompt}",
    "Quiero saber más del Cliente {prompt}",
    "Què saps del cliente {prompt}?",
    "Qué sabes del Cliente {prompt}?",
    "Dona'm detalls del cliente {prompt}",
    "Dame detalles del Cliente {prompt}",
    "M'agradaria veure el historial del liente {prompt}",
    "Quisiera ver el historial del Cliente {prompt}",
    "Perfil del clinete {prompt}",
    "Perfil del Client {prompt}",
    "cli {prompt}",
    "cliente {prompt}",
    "Cli {prompt}",
    "Client {prompt}",
    "Cliente {prompt}",
    "Dades del client {prompt}",
    "Datos del Cliente {prompt}",
    "Dades del client {prompt}"
]

CLIENTES_COMPLETOS_QUERIES = [
    "todo sobre cliente {prompt}",
    "todo del cliente {prompt}",
    "todo info cliente {prompt}",
    "información completo cliente {prompt}",
    "perfil completo cliente {prompt}",
    "datos completo cliente {prompt}",
    "todo sobre client {prompt}",
    "todo del client {prompt}",
    "todo info client {prompt}",
    "informació completa client {prompt}",
    "perfil complet client {prompt}",
    "dades complet client {prompt}",
    "tot sobre cliente {prompt}",
    "tot del cliente {prompt}",
    "tot info cliente {prompt}",
    "tot sobre clietne {prompt}",
    "tot del clietne {prompt}",
    "tot info clietn {prompt}",
    "tot sobre client {prompt}",
    "tot del client {prompt}",
    "tot info client {prompt}",
    "tot sobre clietn {prompt}",
    "tot del clietn {prompt}",
    "tot info clietn {prompt}",
    "perfil completo clietne {prompt}",
    "datos completo clietn {prompt}",
    "perfil complet clint {prompt}",    
    "dame toda la información del cliente {prompt}",
    "quiero todos los detalles del cliente {prompt}",
    "necesito la información completa del cliente {prompt}",
    "mostrar toda la información de {prompt}",
    "¿Qué sabes sobre el cliente {prompt}? Dime todo.",
    "dame el perfil completo del cliente {prompt}",
    "toda la información sobre {prompt}",
    "déjame ver todo sobre el clente {prompt}",
    "quiero ver la ficha completa del cliente {prompt}",
    "info completa del cliente {prompt}",
    "déjame leer todo sobre el cliente {prompt}",
    "dona'm tota la informació del client {prompt}",
    "vull tots els detalls del client {prompt}",
    "necessito la informació completa del client {prompt}",
    "mostra tota la informació de {prompt}",
    "què saps sobre el client {prompt}? Diga'm tot.",
    "dona'm el perfil complet del client {prompt}",
    "tota la informació sobre {prompt}",
    "deixa'm veure tot sobre el clien {prompt}",
    "vull veure la fitxa completa del client {prompt}",
    "info completa del client {prompt}",
    "deixa'm llegir tot sobre el client {prompt}",
    "información íntegra del cliente {prompt}",
    "datos íntegros del cliente {prompt}",
    "vull saber tot sobre el lient {prompt}",
    "informació íntegra del client {prompt}",
    "datos íntegros del client {prompt}"
]

TELEFON_QUERIES = [
    "Qual es el telefono del cliente {prompt}?",
    "Quin telefon te {prompt}?",
    "telefono {prompt}",
    "telefon {prompt}",
    "Teléfono {prompt}",
    "tlefon {prompt}"
    "Telefon de {prompt}",
    "tlf {prompt}",
    "Tlf {prompt}",
    "vull el telfon del client {prompt}",
    "Vull el telefon de {prompt}",
    "quin es el telefn del client {prompt}?",
    "Quin es el telefon de {prompt}?",
    "Podries donar-me el telefon de {prompt}?",
    "podrías darme el teléfono de {prompt}?",
    "Necessito el tlefon de {prompt}",
    "Necesito el teléfono de {prompt}",
    "Em podries dir el telefon de {prompt}?",
    "¿Me podrías decir el teléfono de {prompt}?",
    "Com puc contactar {prompt}? Dona'm el seu telefon.",
    "Cómo puedo contactar a {prompt}? Dame su teléfnoo.",
    "Saps el numero de {prompt}?",
    "Sabes el número de {prompt}?",
    "Quina es la linia directa de {prompt}?",
    "¿Cuál es la línea directa de {prompt}?",
    "Tens el telefn de {prompt}?",
    "Tienes el teléfono de {prompt}?",
    "On puc trobar el tleefon de {prompt}?",
    "¿Dónde puedo encontrar el teléono de {prompt}?",
    "Em pots passar el telefon de {prompt}?",
    "¿Me puedes pasar el teléfono de {prompt}?",
    "telefono {prompt}",
    "telefon {prompt}",
    "Telefon de {prompt}",
    "tlf {prompt}",
    "Tlf {prompt}",
    "M'agradaria saber el telefon de {prompt}",
    "Me gustaría saber el teléfono de {prompt}"
]

EMAIL_QUERIES = [
    "Qual es el email del cliente {prompt}?",
    "email {prompt}",
    "Email {prompt}",
    "emeil {prompt}",
    "correu {prompt}",
    "Correu {prompt}",
    "mail {prompt}",
    "Mail {prompt}",
    "vull el email del client {prompt}",
    "donam el eail de {prompt}",
    "quin es el email del client {prompt}?",
    "quin es el email {prompt}?",
    "Podries donar-me el email de {prompt}?",
    "Necessito el correu de {prompt}",
    "Em podries dir el correu de {prompt}?",
    "On puc trobar el email de {prompt}?",
    "Quina es la adreça electrònica de {prompt}?",
    "Tens el correu de {prompt}?",
    "Em pots passar el email de {prompt}?",
    "M'agradaria saber el email de {prompt}",
    "Correu electrònic de {prompt}",
    "Dame el contacto por email de {prompt}",
    "Vull contactar {prompt} per correu, quin és?",
    "email {prompt}",
    "emil {prompt}",
    "eail {prompt}",        
    "Email {prompt}",
    "correu {prompt}",
    "Correu {prompt}",
    "mail {prompt}",
    "Mail {prompt}",
    "Com puc enviar un email a {prompt}?"
]

DIRECCIO_QUERIES = [
    "Qual es la direccion de {prompt}?",
    "adreça {prompt}",
    "Adreça {prompt}",
    "direcció {prompt}",
    "direccio {prompt}",
    "on es {prompt}",
    "dir {prompt}",
    "vull la direcció {prompt}",
    "quin es l'adreça del client {prompt}?",
    "Podries donar-me la direcció de {prompt}?",
    "Necessito l'adreça de {prompt}",
    "Em podries dir on viu {prompt}?",
    "On puc trobar a {prompt}?",
    "Quina es la ubicació de {prompt}?",
    "Dona'm l'ubicació exacta de {prompt}",
    "On està situat {prompt}?",
    "Vull visitar a {prompt}, quina es la seva adreça?",
    "M'agradaria saber on es localitza {prompt}",
    "Em pots indicar com arribar a {prompt}?",
    "Quin es el punt d'interès més proper a {prompt}?",
    "Dame les coordenades de {prompt}",
    "Quin es el domicili de {prompt}?",
    "adreça {prompt}",
    "Adreça {prompt}",
    "direcció {prompt}",
    "direccio {prompt}",
    "on es {prompt}",
    "dir {prompt}",
    "Com puc arribar a la casa de {prompt}?",
]

CLIENTE_TELEFONO_QUERIES = [
    "De quién es el teléfono {prompt}",
    "¿A qué cliente pertenece el número {prompt}?",
    "Quién tiene el teléfono {prompt}?",
    "Identifica el cliente con el teléfono {prompt}",
    "Cuál es el cliente asociado al número {prompt}?",
    "¿Qué cliente tiene el teléfono {prompt}?",
    "¿A nombre de quién está el número {prompt}?",
    "Dime el cliente del teléfono {prompt}",
    "Quiero saber el cliente del número {prompt}",
    "Cliente con teléfono {prompt}",
    "¿A quién pertenece el número {prompt}?",
    "¿Qué nombre está asociado al teléfono {prompt}?",
    "Nombre del cliente con teléfono {prompt}",
    "¿Conoces al cliente del número {prompt}?",
    "Busca el cliente con teléfono {prompt}",
    "De qui és el telèfon {prompt}?",
    "A quin client pertany el número {prompt}?",
    "Qui té el telèfon {prompt}?",
    "Identifica el client amb el telèfon {prompt}",
    "Quin és el client associat al número {prompt}?",
    "Quin client té el telèfon {prompt}?",
    "A nom de qui està el número {prompt}?",
    "Diga'm el client del telèfon {prompt}",
    "Vull saber el client del número {prompt}",
    "Client amb telèfon {prompt}",
    "A qui pertany el número {prompt}?",
    "Quin nom està associat al telèfon {prompt}?",
    "Nom del client amb telèfon {prompt}",
    "Coneixes al client del número {prompt}?",
    "Busca el client amb telèfon {prompt}"
]

CLIENT_MULTI_QUERIES = [
    "info dels clients {prompt1} i {prompt2}",
    "Informació dels clients {prompt1} i {prompt2}",
    "Detalls del client {prompt1} i del client {prompt2}",
    "Dona'm info dels clients {prompt1} i {prompt2}",
    "Vull dades dels clients {prompt1} i {prompt2}",
    "Qui són els clients {prompt1} i {prompt2}?",
    "Tens dades dels clients {prompt1} i {prompt2}?",
    "Mostra'm els perfils dels clients {prompt1} i {prompt2}",
    "Històric del cleint {prompt1} i del client {prompt2}",
    "Resum del client {prompt1} i del client {prompt2}",
    "info de los clientes {prompt1} y {prompt2}",
    "Información de los clientes {prompt1} y {prompt2}",
    "Detalles del cliente {prompt1} y del cliente {prompt2}",
    "Dame info de los clietes {prompt1} y {prompt2}",
    "Quiero datos de los clientes {prompt1} y {prompt2}",
    "¿Quiénes son los clientes {prompt1} y {prompt2}?",
    "¿Tienes datos de los clientes {prompt1} y {prompt2}?",
    "Muéstrame los perfiles de los clientes {prompt1} y {prompt2}",
    "Historial del cilente {prompt1} y del cliente {prompt2}",
    "Resumen del cliente {prompt1} y del cliente {prompt2}",
    "Info De Los Clientes {prompt1} Y {prompt2}",
    "Datos De Los Clientes {prompt1} Y {prompt2}",
    "Resumen Del Cliente {prompt1} Y Del Cliente {prompt2}",
    "Històric Del Client {prompt1} I Del Client {prompt2}",
    "Mostra'm Els Perfils Dels Clients {prompt1} I {prompt2}",
    "dona'M Info Dels Clients {prompt1} I {prompt2}",
    "vull Dades Dels Clients {prompt1} I {prompt2}",
    "qui Són Els Clients {prompt1} I {prompt2}?"
]    

TELEFON_QUERIES_MULTIPLE = [
    "Qual es el telefono del cliente {prompt1} y del cliente {prompt2}?",
    "Quins telefons tenen {prompt1} i {prompt2}?",
    "telefonos de {prompt1} y {prompt2}",
    "telefons de {prompt1} i {prompt2}",
    "Teléfonos de {prompt1} y {prompt2}",
    "Necessito els telefons de {prompt1} i {prompt2}",
    "Necesito los teléfonos de {prompt1} y {prompt2}",
    "Vull els telefonos dels clients {prompt1} i {prompt2}",
    "Quiero los teléfonos de los clientes {prompt1} y {prompt2}",
    "Pots dir-me els telefons de {prompt1} i {prompt2}?",
    "¿Puedes decirme los teléfonos de {prompt1} y {prompt2}?",
    "Dona'm els telefonos de {prompt1} i {prompt2}",
    "Dame los teléfonos de {prompt1} y {prompt2}",
    "Saps els numeros de {prompt1} i {prompt2}?",
    "Sabes los números de {prompt1} y {prompt2}?",
    "Quina es la línea directa de {prompt1} i {prompt2}?",
    "¿Cuál es la línea directa de {prompt1} y {prompt2}?",
    "Tens els telefons de {prompt1} i {prompt2}?",
    "Tienes los teléfonos de {prompt1} y {prompt2}?",
    "On puc trobar els telefons de {prompt1} i {prompt2}?",
    "¿Dónde puedo encontrar los teléfonos de {prompt1} y {prompt2}?",
    "M'agradaria saber els telefons de {prompt1} i {prompt2}",
    "Me gustaría saber los teléfonos de {prompt1} y {prompt2}"
]

DIRECCIO_QUERIES_MULTIPLE = [
    "Quals són les direccions de {prompt1} i {prompt2}?",
    "Quines adreces tenen {prompt1} i {prompt2}?",
    "adreces de {prompt1} i {prompt2}",
    "direcciones de {prompt1} y {prompt2}",
    "Adreces de {prompt1} i {prompt2}",
    "Necessito les adreces de {prompt1} i {prompt2}",
    "Necesito las direcciones de {prompt1} y {prompt2}",
    "Vull les direccions dels clients {prompt1} i {prompt2}",
    "Quiero las direcciones de los clientes {prompt1} y {prompt2}",
    "Pots dir-me les direccions de {prompt1} i {prompt2}?",
    "¿Puedes decirme las direcciones de {prompt1} y {prompt2}?",
    "Dona'm les adreces de {prompt1} i {prompt2}",
    "Dame las direcciones de {prompt1} y {prompt2}",
    "Saps les adreces de {prompt1} i {prompt2}?",
    "Sabes las direcciones de {prompt1} y {prompt2}?",
    "Quines són les ubicacions de {prompt1} i {prompt2}?",
    "¿Cuáles son las direcciones de {prompt1} y {prompt2}?",
    "tens les direccions de {prompt1} i {prompt2}?",
    "Tienes las direcciones de {prompt1} y {prompt2}?",
    "On puc trobar a {prompt1} i {prompt2}?",
    "¿Dónde puedo encontrar a {prompt1} y {prompt2}?",
    "M'agradaria saber on es localitzen {prompt1} i {prompt2}",
    "Me gustaría saber dónde están situados {prompt1} y {prompt2}",
    "Podries donar-me la ubicació exacta de {prompt1} i {prompt2}?",
    "¿Podrías darme las coordenadas de {prompt1} y {prompt2}?"
]

EMAIL_QUERIES_MULTIPLE = [
    "Quals són els emails dels clients {prompt1} i {prompt2}?",
    "Quels correus tenen {prompt1} i {prompt2}?",
    "emails de {prompt1} y {prompt2}",
    "correus de {prompt1} i {prompt2}",
    "Emails de {prompt1} y {prompt2}",
    "Necessito els correus de {prompt1} i {prompt2}",
    "Necesito los emails de {prompt1} y {prompt2}",
    "Vull els emails dels clients {prompt1} i {prompt2}",
    "Quiero los correos de los clientes {prompt1} y {prompt2}",
    "Pots dir-me els emails de {prompt1} i {prompt2}?",
    "¿Puedes decirme los correos de {prompt1} y {prompt2}?",
    "Dona'm els correus de {prompt1} i {prompt2}",
    "Dame los emails de {prompt1} y {prompt2}",
    "Saps els correus de {prompt1} i {prompt2}?",
    "Sabes los emails de {prompt1} y {prompt2}?",
    "Quines són les adreces electròniques de {prompt1} i {prompt2}?",
    "¿Cuáles son los emails de {prompt1} y {prompt2}?",
    "Tens els correus de {prompt1} i {prompt2}?",
    "Tienes los emails de {prompt1} y {prompt2}?",
    "On puc trobar els correus de {prompt1} i {prompt2}?",
    "¿Dónde puedo encontrar los emails de {prompt1} y {prompt2}?",
    "M'agradaria saber els emails de {prompt1} i {prompt2}",
    "Me gustaría saber los correos de {prompt1} y {prompt2}"
]
