
NUM_FAMILIAS_Q = [
    "¿Cuántas familias de productos tenemos?",
    "Número total de familias",
    "Informe de cantidad de fmilias",
    "Cuantas familias de artículos hay",
    "Total de familias en la empresa",
    "Número de familias de productos existentes",
    "Cantidad de famlias en inventario",
    "Total de famílias de productos",
    "Número de famílias en el catálogo",
    "Informe del total de famílias de productos",
    "¿Cuántas familias de productos tenemos?",
    "Número total de familias",
    "Informe de cantidad de fmilias",
    "Cuantas familias de artículos hay",
    "Total de familias en la empresa",
    "Número de familias de productos existentes",
    "Cantidad de famlias en inventario",
    "Total de famílias de productos",
    "Número de famílias en el catálogo",
    "Informe del total de famílias de productos",
    "Quantes famílies de productes tenim?",
    "Número total de famílies",
    "Informe de quantitat de famíies",
    "Quantes famílies d'articles hi ha",
    "Total de famílies a l'empresa",
    "Número de famílies de productes existents",
    "Quantitat de famíleis en inventari",
    "Total de famílies de productes",
    "Número de famílies en el catàleg",
    "Informe del total de famíleis de productes",
    "¿Cuál es la cantidad de familias de productos?",
    "Informe sobre el número de familas existentes",
    "¿Cuántas famlias hay en total?",
    "Conteo total de familias de productos",
    "Resumen de número de famílias",
    "Informe completo sobre cantidad de fmilias",
    "Cifras totales de familias en la empresa",
    "Informe de familias existetes en la empresa",
    "Total de famlias registradas",
    "Cantidad global de famílias en la empresa",
    "Quina és la quantitat de famílies de productes?",
    "Informe sobre el número de famíleis existents",
    "Quantes famíleis hi ha en total?",
    "Compte total de famílies de productes",
    "Resum de número de famílies",
    "Informe complet sobre quantitat de famíleis",
    "Xifres totals de famílies a l'empresa",
    "Informe de famílies existents a l'empresa",
    "Total de famíleis registrades",
    "Quantitat global de famílies a l'empresa"
]

MARCAS_PRODUCTOS_Q = [
    "¿Cuántas marcas de productos tenemos?",
    "Número total de marcs",
    "Informe de cantidad de mracas",
    "Cuantas marcas de artículos hay",
    "Total de marcas en la empresa",
    "Número de marcas de productos existentes",
    "Cantidad de mracs en inventario",
    "Total de marcs de productos",
    "Número de marcas en el catáogo",
    "Informe del total de marcas de prodctos",
    "Quantes marques de productes tenim?",
    "Número total de mrques",
    "Informe de quantitat de marues",
    "Quantes marques d'articles hi ha",
    "Total de marques a l'empresa",
    "Número de marues de productes existents",
    "Quantitat de maqres en inventari",
    "Total de mrques de productes",
    "Número de maques en el catàleg",
    "Informe del total de marqus de productes",
    "Informe sobre las marcas disponibles",
    "Cantidad total de marcs en la empresa",
    "Resumen del número de mracas",
    "Informe completo de marcas dsiponibles",
    "Número total de marcas en invntario",
    "Lista completa de marcas existetnes",
    "Conteo de marcas de productos",
    "Total de mracs en catálogo",
    "Informe general de marcas registradas",
    "Cantidad de marcas de artíclos",
    "Informe sobre les marques disponibles",
    "Quantitat total de marues a l'empresa",
    "Resum del número de maqres",
    "Informe complet de marques dsiponibles",
    "Número total de maruqes en inventari",
    "Llista completa de maques existents",
    "Compte de marues de productes",
    "Total de maqres en catàleg",
    "Informe general de marques registrades",
    "Quantitat de marques d'artícles",
    "Informe sobre número total de marcs",
    "Qué marcas de productos manejamos?",
    "Cantidad de marcs en la base de datos",
    "Cuantas maracs tenemos registradas?",
    "Recuento total de marcs en la empresa",
    "Cifras totales de maracs disponibles",
    "Resumen de cantidad de marcas existntes",
    "Informe de marcas en el sitema",
    "Número de marcs en la lista de productos",
    "Informe de cantidad de maracs registradas",
    "Informe sobre número total de maruqes",
    "Quines marques de productes gestionem?",
    "Quantitat de maruqes a la base de dades",
    "Quantes marqes tenim registrades?",
    "Recompte total de marques a l'empresa",
    "Xifres totals de maruqes disponibles",
    "Resum de quantitat de marques existetns",
    "Informe de marques al sistema",
    "Número de marqes a la llista de productes",
    "Informe de quantitat de maqres registrades"    
]
