FACT_ANUALES_Q = [
    "Facturación total de la empresa, informe",
    "Necesito la facturación global de la empresa",
    "Informe de facturación total",
    "Cifras totales de facturación",
    "Facturación total acumulada de la empresa",
    "Informe global de facturacón",
    "Facturación de los últimos años",
    "Total facturado en los últimos años",
    "Facturación acumulada en últimos años",
    "Cifras totales en los últimos añso",
    "Quina és la facturació total de l'empresa, informe",
    "Necessito la facturació global de l'empresa",
    "Informe de facturació total",
    "Xifres totals de facturació",
    "Facturació total acumulada de l'empresa",
    "Informe global de faturació",
    "Facturació dels últims anys",
    "Total facturat en els últims anys",
    "Facturació acumulada en últims anys",
    "Xifres totals en els últims anys",
    "Cifras globales de facturación de la empresa",
    "Informe anual de facturación total",
    "Dame el total facturado de la empresa",
    "Facturación total hasta la fecha",
    "Facturación anual resumida",
    "Cifras totales de facturacion últimos años",
    "Informe completo de facturación total",
    "Total facturado en los recientes años",
    "Facturación totales de la empresa, necesito datos",
    "Facturación globla de últimos años",
    "Xifres globals de facturació de l'empresa",
    "Informe anual de facturació total",
    "Dona'm el total facturat de l'empresa",
    "Facturació total fins ara",
    "Facturació anual resumida",
    "Xifres totals de facturació últims anys",
    "Informe complet de facturació total",
    "Total facturat en els anys recents",
    "Facturació totals de l'empresa, necessito dades",
    "Facturació global d'últims anys",
    "Informe sobre facturación globales de la empresa",
    "Resumen de cifras totales facturadas",
    "Dame un informe sobre la facturación total anual",
    "Facturación total reciente de la empresa",
    "Informe consolidado de facturación total",
    "Total de facturación de los pasados años",
    "Cifras de facturación globales hasta la fecha",
    "Informe total de facturación de últimos años",
    "Informe de cifras anuales totales de facturación",
    "Informe d cifras totales facturadas recientemente",
    "Informe sobre facturació globals de l'empresa",
    "Resum de xifres totals facturades",
    "Dona'm un informe sobre la facturació total anual",
    "Facturació total recent de l'empresa",
    "Informe consolidat de facturació total",
    "Total de facturació dels passats anys",
    "Xifres de facturació globals fins ara",
    "Informe total de facturació d'últims anys",
    "Informe de xifres anuals totals de facturació",
    "Informe de xifres totals facturades recentment"    
]

FACT_CY_Q = [
    "¿Cuál es la facturación anual de la empresa?",
    "Facturación anual de la empresa, ¿cuál es?",
    "Empresa, ¿cuál es la facturación anual?",
    "Quina és la facturació anual de l'empresa?",
    "De l'empresa, quina és la facturació anual?",
    "Informe sobre la facturación de la empresa de este año",
    "Este año, informe de facturación de la empresa",
    "Infrome de la facturación de este año de la empresa",
    "Facturación de este año de la empresa, muestra", 
    "Muestra la facturación anual",
    "Mostra la facturació anual",
    "La facturación anual, mostra",
    "Facturació anual, ¿cuánto es?",
    "¿Cuánto es la facturacón anual?", 
    "Cifras anuales en facturación de la empresa",
    "De la empresa, cifras anuales en facturación",
    "¿Cómo está la facturación anual?",
    "La facturación anual, ¿cómo está?",
    "Informe de facturación anual, necesito",
    "Necesito informe de facturación anual",
    "Anual facturación, ¿qué cifras tenemos?", 
    "¿Qué cifras tenemos en facturación anual?",
    "Facturación de la empresa en el año actual",
    "En el año actual, facturación de la empresa",
    "¿En cuánto se cifra la facturación anual?",
    "Se cifra en cuánto la facturación anual?",
    "Facturación de la empresa para el año corriente",
    "Para el año corriente, facturación de la empresa",
    "Resumen anual de facturación, por favor",
    "Por favor, resumen anual de facturación",
    "Informe del año en facturación",
    "En facturación, informe del año",
    "Facturación anual empresa, informa",
    "Facturacón anual empresa, informa",
    "Com està la facturació anual?",
    "La facturació anual, com està?",
    "Informe de facturació anual, necessito",
    "Necessito informe de facturació anual",
    "Facturació anual, quines xifres tenim?",
    "Quines xifres tenim en facturació anual?",
    "Facturació de l'empresa en l'any actual",
    "En l'any actual, facturació de l'empresa",
    "En quant es xifra la facturació anual?",
    "Es xifra en quant la facturació anual?",
    "Facturació de l'empresa per a l'any corrent",
    "Per a l'any corrent, facturació de l'empresa",
    "Resum anual de facturació, si us plau",
    "Si us plau, resum anual de facturació",
    "Informe de l'any en facturació",
    "En facturació, informe de l'any",
    "Facturació anual empresa, informa",
    "Faturació anual empresa, informa"          
]

FACT_SELECTY_Q = [
    "¿Cuál es la facturación de la empresa en el año {prompt}?",
    "Facturación de {prompt}, ¿cuál es para la empresa?",
    "Para el año {prompt}, ¿cuál es la facturación de la empresa?",
    "Informe de facturación de la empresa correspondiente al {prompt}",
    "Necesito el informe de facturación de {prompt} de la empresa",
    "{prompt}, ¿cuál es la facturación de la empresa?",
    "Quina és la facturació de l'empresa en l'any {prompt}?",
    "Facturació de l'any {prompt}, quina és per a l'empresa?",
    "Per a l'any {prompt}, quina és la facturació de l'empresa?",
    "Informe de facturació de l'empresa corresponent a l'{prompt}",
    "Necessito l'informe de facturació de {prompt} de l'empresa",
    "{prompt}, quina és la facturació de l'empresa?",
    "¿Cómo fue la facturación de la empresa en {prompt}?",
    "{prompt}, ¿cómo fue la facturación de la empresa?",
    "Para {prompt}, informe de facturación de la empresa",
    "Informe sobre la facturación de la empresa durante {prompt}",
    "Durante {prompt}, ¿cuál es la facturación de la empresa?",
    "Muestra la facturación de la empresa para {prompt}",
    "{prompt}: necesito cifras de facturación de la empresa",
    "Resumen anual de facturación para el año {prompt}",
    "Cifras de facturación anual para {prompt}, por favor",
    "Por favor, cifras de facturación anual para {prompt}",
    "Com va ser la facturació de l'empresa en {prompt}?",
    "{prompt}, com va ser la facturació de l'empresa?",
    "Per a {prompt}, informe de facturació de l'empresa",
    "Informe sobre la facturació de l'empresa durant {prompt}",
    "Durant {prompt}, quina és la facturació de l'empresa?",
    "Mostra la facturació de l'empresa per a {prompt}",
    "{prompt}: necessito xifres de facturació de l'empresa",
    "Resum anual de facturació per a l'any {prompt}",
    "Xifres de facturació anual per a {prompt}, si us plau",
    "Si us plau, xifres de facturació anual per a {prompt}",
    "Informe anual de {prompt}, ¿cuál es la facturación?",
    "Necesito datos de facturación para el año {prompt}",
    "En el año {prompt}, ¿qué facturación se registró?",
    "Facturación anual de la empresa en {prompt}, informe",
    "{prompt} facturación, ¿cómo se comportó la empresa?",
    "Para el ejercicio de {prompt}, cifras de facturación",
    "Informe de facturación para {prompt}, detalles",
    "Detalles de facturación del año {prompt}",
    "Informe de ingresos anuales de {prompt}",
    "{prompt}, resumen de facturación anual",
    "Informe anual de {prompt}, quina és la facturació?",
    "Necessito dades de facturació per a l'any {prompt}",
    "En l'any {prompt}, quina facturació es va registrar?",
    "Facturació anual de l'empresa en {prompt}, informe",
    "{prompt} facturació, com es va comportar l'empresa?",
    "Per a l'exercici de {prompt}, xifres de facturació",
    "Informe de facturació per a {prompt}, detalls",
    "Detalls de facturació de l'any {prompt}",
    "Informe d'ingressos anuals de {prompt}",
    "{prompt}, resum de facturació anual"    
]


FACT_MULTIPLE_Q = [
    "Facturación de la empresa entre {prompt1} y {prompt2}",
    "Desde {prompt1} hasta {prompt2}, ¿cuál es la facturación?",
    "Facturación anual desde {prompt1} a {prompt2}, necesito datos",
    "Necesito datos de facturación entre {prompt1}, {prompt2} y {prompt3}",
    "Entre los años {prompt1} y {prompt2}, informe de facturación",
    "{prompt1}-{prompt2}, informe de facturación anual",
    "Informe de facturación para los años {prompt1}, {prompt2}",
    "Informe de facturación de {prompt1} a {prompt2}",
    "Facturació de l'empresa entre {prompt1} i {prompt2}",
    "Informe de facturació des de {prompt1} fins a {prompt2}",
    "Quina és la facturació des de {prompt1} fins a {prompt3}?",
    "Des de {prompt1} fins a {prompt2}, quina és la facturació?",
    "Facturació anual des de {prompt1} a {prompt2}, necessito dades",
    "Necessito dades de facturació entre {prompt1}, {prompt2} i {prompt3}",
    "Entre els anys {prompt1} i {prompt2}, informe de facturació",
    "{prompt1}-{prompt2}, informe de facturació anual",
    "Informe de facturació per als anys {prompt1}, {prompt2}",
    "Informe de facturació de {prompt1} a {prompt2}",
    "Facturación de {prompt1} y {prompt2}, informe",
    "Desde {prompt1} a {prompt2}, datos de facturación",
    "Facturación consolidada entre {prompt1} y {prompt2}",
    "{prompt1} y {prompt2}, necesito el resumen de facturación",
    "Informe detallado de facturación de {prompt1} a {prompt2}",
    "Por favor, facturación entre {prompt1}, {prompt2} y {prompt3}",
    "Informe anual entre {prompt1} y {prompt2}, ¿cuál es la facturación?",
    "Facturació de {prompt1} i {prompt2}, informe",
    "Des de {prompt1} a {prompt2}, dades de facturació",
    "Facturació consolidada entre {prompt1} i {prompt2}",
    "{prompt1} i {prompt2}, necessito el resum de facturació",
    "Informe detallat de facturació de {prompt1} a {prompt2}",
    "Xifres anuals entre {prompt1} i {prompt3}, si us plau",
    "Informe financer des de {prompt1} fins a {prompt3}",
    "Si us plau, facturació entre {prompt1}, {prompt2} i {prompt3}",
    "Informe anual entre {prompt1} i {prompt2}, quina és la facturació?",
    "Facturación para los años {prompt1} y {prompt2}",
    "Informe financiero de {prompt1} y {prompt2}",
    "{prompt1} y {prompt2}, datos de facturación",
    "Facturación entre los años {prompt1}, {prompt2} y {prompt3}",
    "Cifras de facturación para {prompt1} y {prompt2}",
    "Informe anual de facturación {prompt1}, {prompt2}",
    "Resumen de facturación de {prompt1} y {prompt2}",
    "Informe anual {prompt1} y {prompt2}, cifras de facturación",
    "Facturació per als anys {prompt1} i {prompt2}",
    "Informe financer de {prompt1} i {prompt2}",
    "{prompt1} i {prompt2}, dades de facturació",
    "Facturació entre els anys {prompt1}, {prompt2} i {prompt3}",
    "Xifres de facturació per a {prompt1} i {prompt2}",
    "Informe anual de facturació {prompt1}, {prompt2}",
    "Resum de facturació de {prompt1} i {prompt2}",
    "Informe anual {prompt1} i {prompt2}, xifres de facturació"
]
