FACT_CURRENT_YEAR_CLIENTES = [
    "facturacion cliente {prompt}",
    "facturacion del client {prompt}",
    "facturacion del cliente {prompt}",
    "fact client {prompt}",
    "Fact cliente {prompt}",
    "client facturacio {prompt}",
    "clente fact {prompt}",
    "¿Cuál es la facturación anual de {prompt} cliente?", 
    "Facturación anual de {prompt}, ¿cuál es?",
    "{prompt} cliente, ¿cuál es la facturación anual?",  
    "Quina és la faturació anual de {prompt}?",  
    "De {prompt}, quina és la facturació anual?",
    "Informe sobre la facturación de {prompt} cliente de este año", 
    "Este año, informe de facturación d {prompt}",  
    "Infrome de la facturación de este año de {prompt}",
    "Facturación de este año de {prompt} client, muestra",  
    "Muestra la facturación anual de {prompt}",
    "Mostra la facturació anual de {prompt} cliente", 
    "La facturación anual de {prompt}, mostra",
    "Facturació anual de {prompt}, ¿cuánto es?",
    "¿Cuánto es la faturacón anual de {prompt}?",  
    "Cifras anuales en facturación de {prompt} cliente",  
    "De {prompt}, cifras anuales en faturación", 
    "¿Cómo está la facturación anual de {prompt}?",
    "La facturación anual de {prompt}, ¿cómo sta?", 
    "Informe de facturación anual de {prompt} cliente, necesito",  
    "Nesecito informe de facturación anual de {prompt}",  
    "{prompt} anual facturación, ¿qué cifras tenmos?",  
    "¿Qué cifras tenemos en facturación anual de {prompt} client?", 
    "Facturación de {prompt} en el año atual", 
    "En el año actual, facturación de {prompt}",
    "¿En cuánto se cifra la faturación anual de {prompt}?",  
    "Se cifra en cuánto la facturación anual de {prompt}?",
    "Facturación de {prompt} cliente para el año corriente",  
    "Para el año corriente, facturación de {prompt}",
    "Resumen anual de facturación de {prompt}, por fabor", 
    "Por favor, resumen anual de faturación de {prompt}", 
    "Informe del año en facturación de {prompt} client", 
    "En facturación, informe del año de {prompt}",
    "Facturación anual de {prompt} empresa, informa",
    "Faturacón anual de {prompt} empresa, informa",  
    "Com està la facturació anual de {prompt}?",  
    "La facturació anual de {prompt}, com sta?", 
    "Informe de faturació anual de {prompt}, necessito",  
    "Necessito informe de facturació anual de {prompt} cliente",  
    "Facturació anual de {prompt}, quines xifres tenm?", 
    "Quines xifres tenim en facturació anual del client {prompt}?",  
    "Facturació de {prompt} en l'any atual",  
    "En l'any actual, facturación de {prompt}",
    "En quant es xifra la faturació anual de {prompt}?",  
    "Es xifra en quant la facturació anual de {prompt}?",
    "Facturació de {prompt} cliente per a l'any corrent", 
    "Per a l'any corrent, facturació de {prompt}",
    "Resum anual de faturació de {prompt}, si us plau", 
    "Si us plau, resum anual de facturación de {prompt} cliente",  
    "Informe de l'any en faturació de {prompt}",  
    "En facturació, informe de l'any de {prompt} client",
]

FACT_ANUALES_CLIENTES = [
    "facturación total de {prompt} cliente",
    "Facturación total de {prompt} cliente",
    "fact total de client {prompt}",
    "Fact total de {prompt} cliente",
    "facturación total del cliente {prompt}",
    "Facturación total cliente {prompt}",    
    "Facturación total de {prompt} cliente, informe",
    "Necesito la facturación global de cliente {prompt}",
    "Informe de facturación total de {prompt}",
    "Cifras totales de facturación de {prompt}",
    "Facturación total acumulada de cliente {prompt}",
    "Informe global de facturacón de {prompt}",
    "Facturación de los últimos años de cliente {prompt}",
    "Total facturado en los últimos años de {prompt}",
    "Facturación acumulada en últimos años de cliente {prompt}",
    "Cifras totales en los últimos añso de {prompt}",
    "Quina és la facturació total de cliente {prompt}, informe",
    "Necessito la facturació global de cliente {prompt}",
    "Informe de facturació total de {prompt}",
    "Xifres totals de facturació de cliente {prompt}",
    "Facturació total acumulada de {prompt}",
    "Informe global de faturació de cliente {prompt}",
    "Facturació dels últims anys de {prompt}",
    "Total facturat en els últims anys de cliente {prompt}",
    "Facturació acumulada en últims anys de {prompt}",
    "Xifres totals en els últims anys de cliente {prompt}",
    "Cifras globales de facturación de {prompt}",
    "Informe anual de facturación total de cliente {prompt}",
    "Dame el total facturado de {prompt}",
    "Facturación total hasta la fecha de cliente {prompt}",
    "Facturación anual resumida de {prompt}",
    "Cifras totales de facturacion últimos años de cliente {prompt}",
    "Informe completo de facturación total de {prompt}",
    "Total facturado en los recientes años de {prompt} cliente",
    "Facturación totales de {prompt}, necesito datos",
    "Facturación globla de últimos años de {prompt}",
    "Xifres globals de facturació de cliente {prompt}",
    "Informe anual de facturació total de {prompt}",
    "Dona'm el total facturat de cliente {prompt}",
    "Facturació total fins ara de {prompt}",
    "Facturació anual resumida de cliente {prompt}",
    "Xifres totals de facturació últims anys de {prompt}",
    "Informe complet de facturació total de cliente {prompt}",
    "Total facturat en els anys recents de {prompt}",
    "Facturació totals de cliente {prompt}, necessito dades",
    "Facturació global d'últims anys de cliente {prompt}",
    "Informe sobre facturación globales de {prompt}",
    "Resumen de cifras totales facturadas de {prompt} cliente",
    "Dame un informe sobre la facturación total de {prompt}",
    "Facturación total reciente de {prompt}",
    "Informe consolidado de facturación total de cliente {prompt}",
    "Total de facturación de los pasados años de {prompt}",
    "Cifras de facturación globales hasta la fecha de cliente {prompt}",
    "Informe total de facturación de últimos años de {prompt}",
    "Informe de cifras anuales totales de facturación del cliente {prompt}",
    "Informe d cifras totales facturadas recientemente de {prompt}",
    "Informe sobre facturació globals de {prompt}",
    "Resum de xifres totals facturades de clente {prompt}",
    "Dona'm un informe sobre la facturació total anual de {prompt}",
    "Facturació total recent de {prompt}",
    "Informe consolidat de facturació total de cliente {prompt}",
    "Total de facturació dels passats anys de {prompt}",
    "Xifres de facturació globals fins ara de cliente {prompt}",
    "Informe total de facturació d'últims anys de {prompt}",
    "Informe de xifres anuals totals de facturació de {prompt} cliente",
    "Informe de xifres totals facturades recentment de {prompt}"
]

GANANCIAS_CURRENT_YEAR_CLIENTES = [
    "ganancias cliente {prompt}",
    "ganancia del client {prompt}",
    "beneficio del cliente {prompt}",
    "guanys del client {prompt}",
    "ganancia client {prompt}",
    "beneficio cliente {prompt}",
    "client guanys {prompt}",
    "client beneficio {prompt}",
    "¿Cuál es la ganancia anual de {prompt} cliente?",
    "Ganancia anual de {prompt}, ¿cuál es?",
    "¿Cuál es el beneficio anual de {prompt}?",
    "Beneficio anual de {prompt}, ¿cuál es?",
    "Quins són els guanys anuals de {prompt}?",
    "De {prompt}, quins són els guanys anuals?",
    "Informe sobre las ganancias de {prompt} cliente de este año",
    "Este año, informe de ganancias de {prompt}",
    "Informe sobre el beneficio de {prompt} de este año",
    "Ganancias de este año de {prompt} client, muestra",
    "Muestra la ganancia anual de {prompt}",
    "Muestra el beneficio anual de {prompt}",
    "Mostra els guanys anuals de {prompt} client",
    "Ganancias anuales de {prompt}, ¿cuánto es?",
    "¿Cuánto es el beneficio anual de {prompt}?",
    "Cifras anuales en ganancias de {prompt} cliente",
    "De {prompt}, cifras anuales en beneficio",
    "¿Cómo está la ganancia anual de {prompt}?",
    "La ganancia anual de {prompt}, ¿cómo está?",
    "Informe de ganancia anual de {prompt} cliente, necesito",
    "Necesito informe de beneficio anual de {prompt}",
    "Quins són els guanys anuals de {prompt}?",
    "Ganancias de {prompt} en el año actual",
    "En el año actual, beneficio de {prompt}",
    "En el año actual, guanys de {prompt}",
    "Ganancia de {prompt} cliente para el año corriente",
    "Para el año corriente, beneficio de {prompt}",
    "Para el año corriente, guanys de {prompt}",
    "Resumen anual de ganancias de {prompt}, por favor",
    "Por favor, resumen anual de beneficio de {prompt}",
    "Si us plau, resum anual de guanys de {prompt} client",
    "Informe del año en ganancias de {prompt} client",
    "En ganancias, informe del año de {prompt}",
    "En beneficio, informe del año de {prompt}",
    "En guanys, informe de l'any de {prompt} client"
]

GANANCIAS_TOTALES_CLIENTES = [
    "ganancias totales de {prompt} cliente",
    "ganancia total del client {prompt}",
    "beneficio total del cliente {prompt}",
    "guanys totals del client {prompt}",
    "ganancia total de client {prompt}",
    "beneficio total de cliente {prompt}",
    "client guanys totals {prompt}",
    "Informe de ganancias totales de {prompt}",
    "Cifras totales de ganancias de {prompt}",
    "Ganancias totales acumuladas de cliente {prompt}",
    "Informe global de ganancias de {prompt}",
    "Ganancias de los últimos años de cliente {prompt}",
    "Total ganado en los últimos años de {prompt}",
    "Ganancias acumuladas en últimos años de cliente {prompt}",
    "Cifras totales en los últimos años de {prompt}",
    "Quins són els guanys totals de cliente {prompt}, informe",
    "Necessito les guanys globals de cliente {prompt}",
    "Informe de guanys totals de {prompt}",
    "Xifres totals de guanys de cliente {prompt}",
    "Guanys totals acumulats de {prompt}",
    "Informe global de guanys de cliente {prompt}",
    "Guanys dels últims anys de {prompt}",
    "Total guanyat en els últims anys de cliente {prompt}",
    "Guanys acumulats en últims anys de {prompt}",
    "Xifres totals en els últims anys de cliente {prompt}",
    "Cifras globales de ganancias de {prompt}",
    "Informe anual de ganancias totales de cliente {prompt}",
    "Dame el total ganado de {prompt}",
    "Ganancias totales hasta la fecha de cliente {prompt}",
    "Ganancias anuales resumidas de {prompt}",
    "Cifras totales de ganancias últimos años de cliente {prompt}",
    "Informe completo de ganancias totales de {prompt}",
    "Total ganado en los recientes años de {prompt} cliente",
    "Ganancias totales de {prompt}, necesito datos",
    "Ganancias globales de últimos años de {prompt}",
    "Xifres globals de guanys de cliente {prompt}",
    "Informe anual de guanys totals de {prompt}",
    "Dona'm el total guanyat de cliente {prompt}",
    "Guanys totals fins ara de {prompt}",
    "Guanys anuals resumits de cliente {prompt}",
    "Xifres totals de guanys últims anys de {prompt}",
    "Informe complet de guanys totals de cliente {prompt}",
    "Total guanyat en els anys recents de {prompt}",
    "Guanys totals de cliente {prompt}, necessito dades",
    "Guanys globals d'últims anys de cliente {prompt}"
]
