ARTICULOS_QUERIES = [
    "art {prompt}",
    "articulo {prompt}",
    "Art {prompt}",
    "Articulo {prompt}",
    "dame información del artículo {prompt}",
    "info del artículo {prompt}",
    "dona'm informació de l'article {prompt}",
    "¿Qué es el artículo {prompt}?",
    "¿Sobre qué trata el artículo {prompt}?",
    "Necessito dades de l'article {prompt}",
    "Tens informació de l'article {prompt}?",
    "detall del article {prompt}",
    "Vull saber més sobre l'article {prompt}",
    "Què saps del artículo {prompt}?",
    "Necesito el resumen del artículo {prompt}",
    "Dona'm un resumen del artículo {prompt}",
    "M'agradaria leer el artículo {prompt}",
    "Info del article {prompt}?",
    "Articulo titulado {prompt}",
    "art {prompt}",
    "articulo {prompt}",
    "Art {prompt}",
    "Articulo {prompt}",
    "Dades del artículo {prompt}"
    "articulo {prompt}",
    "artículo {prompt}",
    "Articulo {prompt}",
    "Artículo {prompt}",
    "article {prompt}",
    "Article {prompt}",
    "art {prompt}",
    "Art {prompt}",
    "Info artículo {prompt}",
    "Info Artículo {prompt}",
    "Detalles {prompt}",
    "detalles {prompt}",
    "Resumen {prompt}",
    "resumen artículo {prompt}",
    "Título {prompt}",
    "título {prompt}",
    "Descripción {prompt}",
    "description {prompt}",
    "art. {prompt}",
    "Art. {prompt}",
    "Información del artículo {prompt}",
    "Dame detalles del artículo {prompt}",
    "Muestra el artículo {prompt}",
    "¿Tienes info sobre el artículo {prompt}?",
    "Quiero saber más sobre el artículo {prompt}",
    "Del artículo {prompt}, ¿qué sabes?",
    "¿Qué dice el artículo {prompt}?",
    "Resumen del artículo {prompt}",
    "Título del artículo {prompt}",
    "Descripción del artículo {prompt}",
    "Dame el resumen del art. {prompt}",
    "Quiero el contenido del Art. {prompt}",
    "Háblame sobre el artículo {prompt}",
    "Informació de l'article {prompt}",
    "Dona'm detalls de l'article {prompt}",
    "Mostra l'article {prompt}",
    "Tens info sobre l'article {prompt}?",
    "Vull saber més sobre l'article {prompt}",
    "De l'article {prompt}, què saps?",
    "Què diu l'article {prompt}?",
    "Resum de l'article {prompt}",
    "Títol de l'article {prompt}",
    "Descripció de l'article {prompt}",
    "Dona'm el resum de l'art. {prompt}",
    "Vull el contingut de l'Art. {prompt}",
    "Explica'm sobre l'article {prompt}",
    "Necessito detalls de l'article {prompt}",    
    "Necesito detalles del artículo {prompt}"
]

PROVEEDOR_QUERIES = [
    "Qui és el proveïdor de l'article {prompt}?",
    "¿Quién es el proveedor del artículo {prompt}?",
    "De qui prové l'article {prompt}?",
    "¿De quién proviene el artículo {prompt}?",
    "Vull saber el proveïdor de {prompt}",
    "Quiero saber el proveedor de {prompt}",
    "On s'adquireix l'article {prompt}?",
    "¿Dónde se adquiere el artículo {prompt}?",
    "Amb qui treballa l'article {prompt}?",
    "¿Con quién trabaja el artículo {prompt}?",
    "De quin proveïdor és {prompt}?",
    "¿De qué proveedor es {prompt}?",
    "De on ve l'article {prompt}?",
    "¿De dónde viene el artículo {prompt}?",
    "Quin és el origen de {prompt}?",
    "¿Cuál es el origen de {prompt}?",
    "Des de quina empresa ve {prompt}?",
    "¿Desde qué empresa viene {prompt}?",
    "Em pots dir el proveïdor de {prompt}?",
    "¿Puedes decirme el proveedor de {prompt}?",
    "Vull informació sobre el proveïdor de {prompt}",
    "Necesito información sobre el proveedor de {prompt}",
    "On es compra {prompt}?",
    "¿Dónde se compra {prompt}?",
    "Provee {prompt}?",
    "Proveïdor {prompt}",
    "Qui proveeix {prompt}?",
    "¿Proveedor {prompt}?",
    "De qui és {prompt}?",
    "¿De quién es {prompt}?",
    "Origen de {prompt}",
    "Font de {prompt}",
    "Empresa de {prompt}",
    "Empresa per {prompt}",
    "Proveïdor del {prompt}",
    "Proveedor de {prompt}",
    "¿De on {prompt}?",
    "¿Dónde se adquiere {prompt}?",
    "Source de {prompt}",
    "Origen {prompt}"    
]

PRECIO_ARTICULOS_QUERIES = [
    "precio art {prompt}",
    "precio articulo {prompt}",
    "Precio art {prompt}",
    "Precio Articulo {prompt}",
    "dame el precio del artículo {prompt}",
    "¿Cuánto cuesta el artículo {prompt}?",
    "preu de l'article {prompt}",
    "¿Qué precio tiene el artículo {prompt}?",
    "Dime el precio del artículo {prompt}",
    "Quant val l'article {prompt}?",
    "Tienes el precio de l'article {prompt}?",
    "preu del article {prompt}",
    "Vull saber el preu de l'article {prompt}",
    "Què costa el artículo {prompt}?",
    "Necesito el precio del artículo {prompt}",
    "Dona'm el preu del artículo {prompt}",
    "Quiero comprar el artículo {prompt}, ¿cuánto cuesta?",
    "Precio del artículo {prompt}?",
    "Articulo {prompt} precio",
    "precio art {prompt}",
    "precio articulo {prompt}",
    "Precio art {prompt}",
    "Precio Articulo {prompt}",
    "Precio del artículo {prompt}",
    "precio articulo {prompt}",
    "precio artículo {prompt}",
    "Precio Articulo {prompt}",
    "Precio Artículo {prompt}",
    "preu article {prompt}",
    "Preu Article {prompt}",
    "precio art {prompt}",
    "Precio art {prompt}",
    "Info precio artículo {prompt}",
    "Info Precio Artículo {prompt}",
    "Precio {prompt}",
    "precio {prompt}",
    "Coste {prompt}",
    "coste artículo {prompt}",
    "Valor {prompt}",
    "valor {prompt}",
    "Cuánto cuesta {prompt}",
    "cuánto cuesta {prompt}",
    "art. {prompt} precio",
    "Art. {prompt} precio",
    "Información del precio del artículo {prompt}",
    "Dame el precio del artículo {prompt}",
    "¿Cuánto vale el artículo {prompt}?",
    "¿Tienes el precio del artículo {prompt}?",
    "Quiero saber el precio del artículo {prompt}",
    "Del artículo {prompt}, ¿cuánto cuesta?",
    "¿Qué coste tiene el artículo {prompt}?",
    "Valor del artículo {prompt}",
    "Precio del artículo {prompt}",
    "Coste del artículo {prompt}",
    "Dime el precio del art. {prompt}",
    "Quiero el precio del Art. {prompt}",
    "Cuéntame cuánto cuesta el artículo {prompt}",
    "Informació del preu de l'article {prompt}",
    "Dona'm el preu de l'article {prompt}",
    "¿Què val l'article {prompt}?",
    "Tens el preu de l'article {prompt}?",
    "Vull conèixer el preu de l'article {prompt}",
    "De l'article {prompt}, quant costa?",
    "Què val l'article {prompt}?",
    "Valor de l'article {prompt}",
    "Preu de l'article {prompt}",
    "Cost de l'article {prompt}",
    "Dona'm el preu de l'art. {prompt}",
    "Vull el preu de l'Art. {prompt}",
    "Explica'm quant val l'article {prompt}",
    "Necessito el preu de l'article {prompt}",    
    "Necesito el precio del artículo {prompt}"
]

ARTICULOS_COMPLETOS_QUERIES = [
    "dame toda la información del artículo {prompt}",
    "tot info art {prompt}",
    "tota la info article {prompt}",    
    "toda la info de articu {prompt}",
    "toda la info articulo {prompt}",
    "quiero todos los detalles del artículo {prompt}",
    "necesito la información completa del artículo {prompt}",
    "mostrar toda la información de {prompt}",
    "¿Qué sabes sobre el artículo {prompt}? Dime todo.",
    "dame el contenido completo del artículo {prompt}",
    "toda la información sobre {prompt}",
    "déjame ver todo sobre el artículo {prompt}",
    "quiero ver la ficha completa del artículo {prompt}",
    "info completa del artículo {prompt}",
    "déjame leer todo el artículo {prompt}",
    "dona'm tota la informació de l'article {prompt}",
    "vull tots els detalls de l'article {prompt}",
    "necessito la informació completa de l'article {prompt}",
    "mostra tota la informació de article {prompt}",
    "què saps sobre l'article {prompt}? Diga'm tot.",
    "dona'm el contingut complet de l'article {prompt}",
    "tota informació sobre art {prompt}",
    "deixa'm veure tot sobre l'article {prompt}",
    "vull veure la fitxa completa de l'article {prompt}",
    "info completa de l'article {prompt}",
    "deixa'm llegir tot l'article {prompt}",
    "información íntegra del artículo {prompt}",
    "datos íntegros del artículo {prompt}",
    "vull saber tot sobre l'article {prompt}",
    "informació íntegra de l'article {prompt}",
    "datos íntegros de l'article {prompt}"
]
