ARTICULOS_QUERIES = [
    "art {prompt}",
    "articulo {prompt}",
    "Art {prompt}",
    "Articulo {prompt}",
    "producte {prompt}",
    "Producto {prompt}",
    "art {prompt}, dame info",
    "articulo {prompt} cuanto estoc tenemos",
    "Art {prompt}",
    "Articulo {prompt} dime más",    
    "dame información del artículo {prompt}",
    "info del artículo {prompt}",
    "dona'm informació de l'article {prompt}",
    "¿Qué es el artículo {prompt}?",
    "¿Sobre qué trata el artículo {prompt}?",
    "Necessito dades de l'article {prompt}",
    "Tens informació de l'article {prompt}?",
    "detall del article {prompt}",
    "Vull saber més sobre l'article {prompt}",
    "Què saps del artículo {prompt}?",
    "Necesito el resumen del artículo {prompt}",
    "Dona'm un resumen del artículo {prompt} siusplau",
    "M'agradaria leer el artículo {prompt}",
    "Info del article {prompt}?",
    "Articulo titulado {prompt}",
    "art {prompt}",
    "art {prompt} dame su información",
    "articulo {prompt}",
    "articulo {prompt}, info basica",
    "Art {prompt}",
    "Articulo {prompt}",
    "Articulo {prompt} dame su info",
    "Dades del artículo {prompt}"
    "Dades del artículo {prompt} siusplau"
    "articulo {prompt}",
    "artículo {prompt}",
    "Articulo {prompt}",
    "Artículo {prompt}",
    "article {prompt}",
    "Article {prompt}",
    "art {prompt}",
    "Art {prompt}",
    "Info producto {prompt}",
    "Info artículo {prompt} porfavor",
    "Info Artículo {prompt}",
    "Detalles art {prompt}",
    "detalles articulo {prompt}",
    "detalles producto {prompt} porfabor",
    "Resumen del articlo {prompt}",
    "resumen artículo {prompt}",
    "info producto {prompt}",
    "producto {prompt}, dame la info",
    "Descripción art {prompt}",
    "description articulo {prompt}",
    "art. {prompt}",
    "Art. {prompt}",
    "Información del artículo {prompt}",
    "Dame detalles del artículo {prompt}",
    "Muestra el artículo {prompt}",
    "¿Tienes info sobre el producto {prompt}?",
    "Quiero saber más sobre el artículo {prompt}",
    "Del artículo {prompt}, ¿qué sabes?",
    "¿Qué dice el artículo {prompt}?",
    "Resumen del artículo {prompt}",
    "Título del artículo {prompt}",
    "Descripción del artículo {prompt}",
    "Dame el resumen del art. {prompt}",
    "Quiero el contenido del Art. {prompt}",
    "Háblame sobre el artículo {prompt}",
    "Informació de l'article {prompt}",
    "Dona'm detalls de l'article {prompt}",
    "Mostra l'article {prompt}",
    "Tens info sobre l'article {prompt}?",
    "Vull saber més sobre el producte {prompt}",
    "De l'article {prompt}, què saps?",
    "Què diu l'article {prompt}?",
    "Resum de l'article {prompt}",
    "Títol del producte {prompt}",
    "Descripció de l'article {prompt}",
    "Dona'm el resum de l'art. {prompt}",
    "Vull el contingut de l'Art. {prompt}",
    "Explica'm sobre l'article {prompt}",
    "Necessito detalls de l'article {prompt}",    
    "Necesito detalles del artículo {prompt}",
    "Necessito detalls de l'article {prompt} siusplau",    
    "Necesito detalles del artículo {prompt} porfavor"    
]

PROVEEDOR_QUERIES = [
    "Qui és el proveïdor de l'article {prompt}?",
    "¿Quién es el proveedor del artículo {prompt}?",
    "De qui prové l'article {prompt}?",
    "¿De quién proviene el artículo {prompt}?",
    "Vull saber el proveïdor de {prompt}",
    "Quiero saber el proveedor de {prompt}",
    "On s'adquireix l'article {prompt}?",
    "¿Dónde se adquiere el artículo {prompt}?",
    "Amb qui treballa l'article {prompt}?",
    "¿Con quién trabaja el artículo {prompt}?",
    "De quin proveïdor és {prompt}?",
    "¿De qué proveedor es {prompt}?",
    "De on ve l'article {prompt}?",
    "¿De dónde viene el artículo {prompt}?",
    "Quin és el origen de {prompt}?",
    "¿Cuál es el origen de {prompt}?",
    "Des de quina empresa ve {prompt}?",
    "¿Desde qué empresa viene {prompt}?",
    "Em pots dir el proveïdor de {prompt}?",
    "¿Puedes decirme el proveedor de {prompt}?",
    "Vull informació sobre el proveïdor de {prompt}",
    "Necesito información sobre el proveedor de {prompt}",
    "On es compra {prompt}?",
    "¿Dónde se compra {prompt}?",
    "Provee {prompt}?",
    "Proveïdor {prompt}",
    "Qui proveeix {prompt}?",
    "¿Proveedor {prompt}?",
    "De qui és {prompt}?",
    "¿De quién es {prompt}?",
    "Origen de {prompt}",
    "Font de {prompt}",
    "Empresa de {prompt}",
    "Empresa per {prompt}",
    "Proveïdor del {prompt}",
    "Proveedor de {prompt}",
    "¿De on {prompt}?",
    "¿Dónde se adquiere {prompt}?",
    "Source de {prompt}",
    "Origen {prompt}"    
]

PRECIO_ARTICULOS_QUERIES_COSTE = [
    "precio cost art {prompt}",
    "precio coste art {prompt}",
    "precio de coste art {prompt}",
    "coste art {prompt}",
    "precio articulo {prompt}, que coste tiene",
    "precio compra articulo {prompt}",
    "precio de compra articulo {prompt}",
    "precio coste articulo {prompt}",
    "coste articulo {prompt}",
    "coste producto {prompt}",
    "Precio compra art {prompt}",
    "Precio compra producto {prompt}",
    "Cost art {prompt}",
    "Precio compra Articulo {prompt}",
    "Coste Articulo {prompt}",
    "dame el precio del artículo {prompt}, la compra",
    "dame el coste del artículo {prompt}",
    "¿Cuánto cuesta el artículo {prompt}?",
    "¿Cuánto vale en coste el artículo {prompt}?",
    "preu cost de l'article {prompt}",
    "preu cost de article {prompt}",
    "cost de l'article {prompt}",
    "¿Qué precio tiene el producto {prompt}?",
    "¿Qué coste tiene el artículo {prompt}?",
    "Dime el precio de compra del artículo {prompt}",
    "Dime el coste del artículo {prompt}",
    "Quant val l'article {prompt}?",
    "Quant costa en cost l'article {prompt}?",
    "Tienes el precio de compra l'article {prompt}?",
    "Tienes el coste de l'article {prompt}?",
    "preu compra del article {prompt}",
    "cost del article {prompt}",
    "Vull saber el preu compra de l'article {prompt}",
    "Vull saber el cost de l'article {prompt}",
    "Què costa el artículo {prompt}?",
    "Què val en coste el artículo {prompt}?",
    "Necesito el precio de compra del producto {prompt}",
    "Necesito el coste del artículo {prompt}",
    "Dona'm el preu de cost del artículo {prompt}",
    "Dona'm el cost del artículo {prompt}",
    "compra de Precio del artículo {prompt}?",
    "Coste del artículo {prompt}?",
    "Articulo {prompt} precio de coste",
    "Article {prompt} preu cost",
    "Articulo {prompt} coste",
    "Producto {prompt} coste",
    "producto {prompt} coste",
    "Articulo {prompt} precio compra",
    "Información del precio de csote del artículo {prompt}",
    "Dame el precio del artículo {prompt}, su rpecio de compra",
    "Dame el precio del artículo {prompt} porfavor",
    "¿Cuánto vale el artículo {prompt}?",
    "¿Tienes el precio compra del artículo {prompt}?",
    "Quiero saber el precio del coste del artículo {prompt}",
    "Del artículo {prompt}, ¿cuánto cuesta?",
    "¿Qué coste tiene el artículo {prompt}?",
    "Valor del artículo {prompt}",
    "Precio de coste del artículo {prompt}",
    "Coste del artículo {prompt}",
    "Dime el precio de compra del art. {prompt}",
    "Quiero el precio coste del Art. {prompt}",
    "Cuéntame cuánto cuesta el producto {prompt}",
    "Informació del preu de cost de l'article {prompt}",
    "Dona'm el preu compar de l'article {prompt}",
    "Dona'm el preu compar de producte {prompt}",
    "¿Què val l'article {prompt}?",
    "Tens el preu de csot de l'article {prompt}?",
    "Vull conèixer el preu ed compra de l'article {prompt}",
    "De l'article {prompt}, quant costa?",
    "Què val l'article {prompt}?",
    "Valor de l'article {prompt}",
    "Preu de l'article {prompt}, en cost",
    "Cost del producte {prompt}",
    "Dona'm el preu de l'art. {prompt} vull el preu de compra",
    "Vull el preu de l'Art. {prompt}",
    "Explica'm quant val l'article {prompt}",
    "Necessito el preu de cost de l'article {prompt}",    
    "Necesito el precio cmpra del artículo {prompt}"
]

PRECIO_ARTICULOS_QUERIES_VENTA = [
    "precio venta art {prompt}",
    "precio de venta art {prompt}",
    "venta art {prompt}",
    "precio articulo {prompt}, que venta tiene",
    "precio producto {prompt}, que venta tiene",
    "precio venta articulo {prompt}",
    "precio de venta articulo {prompt}",
    "venta articulo {prompt}",
    "Precio venta art {prompt}",
    "Venta art {prompt}",
    "Precio venta Articulo {prompt}",
    "Venta Articulo {prompt}",
    "dame el precio del artículo {prompt}, la venta",
    "dame la venta del artículo {prompt}",
    "¿Cuánto cuesta el artículo {prompt} en venta?",
    "¿Cuánto vale en venta el artículo {prompt}?",
    "preu venta de l'article {prompt}",
    "preu venda de l'article {prompt}",
    "preu venda de producte {prompt}",
    "venda de l'article {prompt}",
    "¿Qué precio de venta tiene el artículo {prompt}?",
    "Dime el precio de venta del artículo {prompt}",
    "Quant val l'article {prompt} en venda?",
    "Tienes el precio de venta prodcuto {prompt}?",
    "Tienes la venda de l'article {prompt}?",
    "preu venda del article {prompt}",
    "venda del article {prompt}",
    "Vull saber el preu venda de l'article {prompt}",
    "Vull saber la venda de l'article {prompt}",
    "Què costa el artículo {prompt} en venta?",
    "Necesito el precio de venta del artículo {prompt}",
    "Dona'm el preu de venda del artículo {prompt}",
    "Dona'm la venda del artículo {prompt}",
    "venta de Precio del artículo {prompt}?",
    "Venta del artículo {prompt}?",
    "Articulo {prompt} precio de venta",
    "Article {prompt} preu venda",
    "Articulo {prompt} venta",
    "Prducto {prompt} venta",
    "producto {prompt} venta",
    "Articulo {prompt} precio venta",
    "Información del precio de venta del artículo {prompt}",
    "Dame el precio del artículo {prompt}, su precio de venta",
    "Dame el precio del artículo {prompt} por favor",
    "¿Cuánto vale el artículo {prompt} en venta?",
    "¿Tienes el precio venta del artículo {prompt}?",
    "Quiero saber el precio de venta del artículo {prompt}",
    "Del artículo {prompt}, ¿cuánto cuesta en venta?",
    "¿Qué venta tiene el artículo {prompt}?",
    "Valor de venta del artículo {prompt}",
    "Precio de venta del artículo {prompt}",
    "Venta del artículo {prompt}",
    "Dime el precio de venta del art. {prompt}",
    "Quiero el precio venta del Art. {prompt}",
    "Cuéntame cuánto cuesta el artículo {prompt} en venta",
    "Informació del preu de venda de l'article {prompt}",
    "Dona'm el preu venda de l'article {prompt}",
    "¿Què val l'article {prompt} en venda?",
    "Tens el preu de venda de l'article {prompt}?",
    "Vull conèixer el preu de venda de l'article {prompt}",
    "De l'article {prompt}, quant costa en venda?",
    "Venda de l'article {prompt}",
    "Dona'm el preu de l'art. {prompt}, vull el preu de venta",
    "Vull el preu de l'Art. {prompt} en venda",
    "Explica'm quant val l'article {prompt} en venda",
    "Necessito el preu de venda de l'article {prompt}",
    "Necesito el precio venta del artículo {prompt}"
]

ARTICULOS_COMPLETOS_QUERIES = [
    "dame toda la información del artículo {prompt}",
    "dame toda información del producto {prompt}",
    "tot info art {prompt}",
    "tota la info article {prompt}",    
    "tota la info producte {prompt}",    
    "tota info article {prompt}, vull saber el proveidor, marca i familia",    
    "tota la info article {prompt}, me interesa el precio de compra y la familia",    
    "tota la info article {prompt}, donam el preu de venda i de cost",    
    "toda la info de articu {prompt}",
    "toda la info articulo {prompt}",
    "toda la info producto {prompt}",
    "toda la info articulo {prompt}, quiero el codigo de barras y el precio coste",
    "toda la info articulo {prompt}, dame su stock y precio de venta",
    "toda la info articulo {prompt} porfavor",
    "dame toda la información del artículo {prompt} porfavro",
    "quiero todos los detalles del artículo {prompt}",
    "necesito la información completa del artículo {prompt}",
    "mostrar toda la información de {prompt}",
    "¿Qué sabes sobre el artículo {prompt}? Dime todo.",
    "dame el contenido completo del artículo {prompt}",
    "toda la información sobre {prompt}",
    "déjame ver todo sobre el artículo {prompt}",
    "Quiero ver todo del artículo {prompt}",
    "Quiero todo del artículo {prompt}",
    "Quiero todo del producto {prompt}",
    "déjame ver todo sobre el producto {prompt}",
    "déjame ver todo del producto {prompt}",
    "quiero ver la ficha completa del artículo {prompt}",
    "info completa del artículo {prompt}",
    "info complta del prodcuto {prompt}",
    "déjame leer todo el artículo {prompt}",
    "dona'm tota la informació de l'article {prompt}",
    "vull tots els detalls de l'article {prompt}",
    "necessito la informació completa de l'article {prompt}",
    "mostra tota la informació de aritcle {prompt}",
    "què saps sobre l'article {prompt}? Diga'm tot.",
    "dona'm el contingut complet de l'article {prompt}",
    "tota informació sobre art {prompt}",
    "tota informació sobre art {prompt}, siusplau",
    "deixa'm veure tot sobre l'article {prompt}",
    "deixa'm veure tot sobre l'article {prompt} siusplau",
    "vull veure la fitxa completa de l'article {prompt}",
    "info completa de l'article {prompt}",
    "info completa de l'article {prompt} siusplau",
    "deixa'm llegir tot l'article {prompt}",
    "información íntegra del artículo {prompt}",
    "datos íntegros del artículo {prompt}",
    "vull saber tot sobre l'article {prompt}",
    "informació íntegra de l'article {prompt}",
    "datos íntegros de l'article {prompt}"
]
