ARTICULOS_QUERIES = [
    "art {prompt}",
    "articulo {prompt}",
    "Art {prompt}",
    "Articulo {prompt}",
    "dame información del artículo {prompt}",
    "info del artículo {prompt}",
    "dona'm informació de l'article {prompt}",
    "¿Qué es el artículo {prompt}?",
    "¿Sobre qué trata el artículo {prompt}?",
    "Necessito dades de l'article {prompt}",
    "Tens informació de l'article {prompt}?",
    "detall del article {prompt}",
    "Vull saber més sobre l'article {prompt}",
    "Què saps del artículo {prompt}?",
    "Necesito el resumen del artículo {prompt}",
    "Dona'm un resumen del artículo {prompt}",
    "M'agradaria leer el artículo {prompt}",
    "Info del article {prompt}?",
    "Articulo titulado {prompt}",
    "art {prompt}",
    "articulo {prompt}",
    "Art {prompt}",
    "Articulo {prompt}",
    "Dades del artículo {prompt}"
    "articulo {prompt}",
    "artículo {prompt}",
    "Articulo {prompt}",
    "Artículo {prompt}",
    "article {prompt}",
    "Article {prompt}",
    "art {prompt}",
    "Art {prompt}",
    "Info artículo {prompt}",
    "Info Artículo {prompt}",
    "Detalles {prompt}",
    "detalles {prompt}",
    "Resumen {prompt}",
    "resumen artículo {prompt}",
    "Título {prompt}",
    "título {prompt}",
    "Descripción {prompt}",
    "description {prompt}",
    "art. {prompt}",
    "Art. {prompt}",
    "Información del artículo {prompt}",
    "Dame detalles del artículo {prompt}",
    "Muestra el artículo {prompt}",
    "¿Tienes info sobre el artículo {prompt}?",
    "Quiero saber más sobre el artículo {prompt}",
    "Del artículo {prompt}, ¿qué sabes?",
    "¿Qué dice el artículo {prompt}?",
    "Resumen del artículo {prompt}",
    "Título del artículo {prompt}",
    "Descripción del artículo {prompt}",
    "Dame el resumen del art. {prompt}",
    "Quiero el contenido del Art. {prompt}",
    "Háblame sobre el artículo {prompt}",
    "Informació de l'article {prompt}",
    "Dona'm detalls de l'article {prompt}",
    "Mostra l'article {prompt}",
    "Tens info sobre l'article {prompt}?",
    "Vull saber més sobre l'article {prompt}",
    "De l'article {prompt}, què saps?",
    "Què diu l'article {prompt}?",
    "Resum de l'article {prompt}",
    "Títol de l'article {prompt}",
    "Descripció de l'article {prompt}",
    "Dona'm el resum de l'art. {prompt}",
    "Vull el contingut de l'Art. {prompt}",
    "Explica'm sobre l'article {prompt}",
    "Necessito detalls de l'article {prompt}",    
    "Necesito detalles del artículo {prompt}"
]

PROVEEDOR_QUERIES = [
    "Qui és el proveïdor de l'article {prompt}?",
    "¿Quién es el proveedor del artículo {prompt}?",
    "De qui prové l'article {prompt}?",
    "¿De quién proviene el artículo {prompt}?",
    "Vull saber el proveïdor de {prompt}",
    "Quiero saber el proveedor de {prompt}",
    "On s'adquireix l'article {prompt}?",
    "¿Dónde se adquiere el artículo {prompt}?",
    "Amb qui treballa l'article {prompt}?",
    "¿Con quién trabaja el artículo {prompt}?",
    "De quin proveïdor és {prompt}?",
    "¿De qué proveedor es {prompt}?",
    "De on ve l'article {prompt}?",
    "¿De dónde viene el artículo {prompt}?",
    "Quin és el origen de {prompt}?",
    "¿Cuál es el origen de {prompt}?",
    "Des de quina empresa ve {prompt}?",
    "¿Desde qué empresa viene {prompt}?",
    "Em pots dir el proveïdor de {prompt}?",
    "¿Puedes decirme el proveedor de {prompt}?",
    "Vull informació sobre el proveïdor de {prompt}",
    "Necesito información sobre el proveedor de {prompt}",
    "On es compra {prompt}?",
    "¿Dónde se compra {prompt}?",
    "Provee {prompt}?",
    "Proveïdor {prompt}",
    "Qui proveeix {prompt}?",
    "¿Proveedor {prompt}?",
    "De qui és {prompt}?",
    "¿De quién es {prompt}?",
    "Origen de {prompt}",
    "Font de {prompt}",
    "Empresa de {prompt}",
    "Empresa per {prompt}",
    "Proveïdor del {prompt}",
    "Proveedor de {prompt}",
    "¿De on {prompt}?",
    "¿Dónde se adquiere {prompt}?",
    "Source de {prompt}",
    "Origen {prompt}"    
]
