ALBARAN_QUERIES = [
    "Alb {prompt}, dame informacion relevante",
    "alb {prompt}",
    "alb {prompt}, quin es el marge",    
    "albarà {prompt}",
    "Albarà {prompt}",
    "albara {prompt}, de quin client es",
    "Albara {prompt}",    
    "albra {prompt}",
    "Abarà {prompt}",
    "alara {prompt}",
    "Albar {prompt}",   
    "Quin és l'albarà {prompt}?",
    "vull més info de l'albarà {prompt}",
    "Em pots donar detalls de l'albarà {prompt}?",
    "Necessito l'albarà número {prompt}",
    "On puc trobar l'albarà {prompt}?",
    "Com puc accedir a l'albarà {prompt}?",
    "Dona'm l'estat de l'albarà {prompt}",
    "M'agradaria veure l'albarà {prompt}",
    "Em pots enviar una còpia de l'albara {prompt}?",
    "Vull revisar l'albarà {prompt}",
    "¿Cuál es el albarán {prompt}?",
    "quiero más información del albarán {prompt}",
    "Necesito el albarán número {prompt}",
    "¿Dónde puedo encontrar el albarán {prompt}?",
    "¿Cómo puedo acceder al alarán {prompt}?",
    "Dame el estado del albarán {prompt}",
    "Me gustaría ver el albarn {prompt}",
    "¿Puedes enviarme una copia del albarán {prompt}?",
    "Quiero revisar el albarán {prompt}",
    "Necesito confirmar el albarán {prompt}",
    "¿Puedo ver el albarán {prompt}?",
    "¿Tienes disponible el albarán {prompt}?",    
    "Alb {prompt}",
    "alb {prompt}",
    "albarà {prompt}",
    "Albarà {prompt}",
    "Puc obtenir una còpia de l'albarà {prompt}?",
    "{prompt} albarà?",
    "Detalls albarà {prompt}",
    "Estat albarà {prompt}?",
    "Vull albarà {prompt}",
    "Revisar albarà {prompt}",
    "Número albarà {prompt}?",
    "Albarà {prompt} disponible?",
    "Veure albarà {prompt}",
    "Albarán {prompt}",
    "Alb {prompt}",
    "{prompt} albarán?",
    "{prompt} ver albarán",
    "{prompt} dame albarán",
    "{prompt} dime albarán",
    "{prompt} info albarán",
    "{prompt} info albaran",
    "{prompt} info Albaran",
    "{prompt} Info Albaran",
    "Info albarán {prompt}",
    "Estado albarán {prompt}?",
    "Ver albarán {prompt}",
    "Revisar albarán {prompt}",
    "Número albarán {prompt}?",
    "Albarán {prompt} disponible?",
    "Consultar albarán {prompt}",
    "{prompt} albara?",
    "{prompt} és l'albara?",
    "{prompt} albara disponible?",
    "{prompt} albara estat?",
    "{prompt} albara info?",
    "{prompt} veure albara",
    "{prompt} copia albarà",
    "{prompt} número albarà",
    "{prompt} revisar albara",
    "{prompt} albarán?",
    "{prompt} es el albarán?",
    "{prompt} albarán disponible?",
    "{prompt} albarán estado?",
    "{prompt} info albarán?",
    "{prompt} ver albarán",
    "{prompt} copia albarán",
    "{prompt} número albarán",
    "{prompt} revisar albaran"   
]

ALB_CLIENT_DETAIL = [
    "{prompt} revisar albaran"   

]

PEDIDOS_QUERIES = [
    "Ped {prompt}",
    "ped {prompt}",
    "comanda {prompt}",
    "Comanda {prompt}",
    "Quin és el pedido {prompt}?",
    "vull més info de la comanda {prompt}",
    "Em pots donar detalls de la comanda {prompt}?",
    "Necessito la comanda número {prompt}",
    "On puc trobar la comanda {prompt}?",
    "Com puc accedir a la comanda {prompt}?",
    "Dona'm l'estat de la comanda {prompt}",
    "M'agradaria veure la comanda {prompt}",
    "Em pots enviar una còpia de la comanda {prompt}?",
    "Vull revisar la comanda {prompt}",
    "Necessito confirmar la comanda {prompt}",
    "Puc veure la comanda {prompt}?",
    "Tens la comanda {prompt} disponible?",
    "Ped {prompt}",
    "ped {prompt}",
    "pedido {prompt}",
    "Pedido {prompt}",
    "¿Puedo obtener una copia del pedido {prompt}?"
]

FACTURAS_QUERIES = [
    "Fact {prompt}",
    "fact {prompt}",
    "factura {prompt}",
    "Factura {prompt}",
    "Quina és la factura {prompt}?",
    "vull més info de la factura {prompt}",
    "Em pots donar detalls de la factura {prompt}?",
    "Necessito la factura número {prompt}",
    "On puc trobar la factura {prompt}?",
    "Com puc accedir a la factura {prompt}?",
    "Dona'm l'estat de la factura {prompt}",
    "M'agradaria veure la factura {prompt}",
    "Em pots enviar una còpia de la factura {prompt}?",
    "Vull revisar la factura {prompt}",
    "Necessito confirmar la factura {prompt}",
    "Puc veure la factura {prompt}?",
    "Tens la factura {prompt} disponible?",
    "Em pots mostrar la factura {prompt}?",
    "Fact {prompt}",
    "fact {prompt}",
    "factura {prompt}",
    "Factura {prompt}",
    "¿Puedo obtener una copia de la factura {prompt}?"
]
